import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

class gui{
    public static void main(String args[]){
		
       JFrame frame = new JFrame("Checkers");
       
       JButton btn1 = new JButton("");
	   JButton btn2 = new JButton("");
	   JButton btn3 = new JButton("");
	   JButton btn4 = new JButton(" 4");
	   JButton btn5 = new JButton("Press 5");
	   JButton btn6 = new JButton("Press 6");
	   JButton btn7 = new JButton(" 7");
	   JButton btn8 = new JButton("Press 8");
	   JButton btn9 = new JButton("Press 1");
	   JButton btn10 = new JButton("Press 2");
	   JButton btn11 = new JButton("Press 3");
	   JButton btn12 = new JButton("Press 4");
	   JButton btn13 = new JButton("Press 5");
	   JButton btn14 = new JButton("Press 6");
	   JButton btn15 = new JButton("Press 7");
	   JButton btn16 = new JButton("Press 8");
	   JButton btn17 = new JButton("Press 1");
	   JButton btn18= new JButton("Press 2");
	   JButton btn19= new JButton("Press 3");
	   JButton btn20= new JButton("Press 4");
	   JButton btn21= new JButton("Press 5");
	   JButton btn22= new JButton("Press 6");
	   JButton btn23= new JButton("Press 7");
	   JButton btn24= new JButton("Press 8");
	   JButton btn25= new JButton("Press 1");
	   JButton btn26 = new JButton("Press 2");
	   JButton btn27 = new JButton("Press 3");
	   JButton btn28 = new JButton("Press 4");
	   JButton btn29 = new JButton("Press 5");
	   JButton btn30 = new JButton("Press 6");
	   JButton btn31 = new JButton("Press 7");
	   JButton btn32 = new JButton("Press 8");
	   JButton btn33= new JButton("Press 1");
	   JButton btn34= new JButton("Press 2");
	   JButton btn35= new JButton("Press 3");
	   JButton btn36= new JButton("Press 4");
	   JButton btn37= new JButton("Press 5");
	   JButton btn38= new JButton("Press 6");
	   JButton btn39= new JButton("Press 7");
	   JButton btn40= new JButton("Press 8");
	   JButton btn41= new JButton("Press 1");
	   JButton btn42 = new JButton("Press 2");
	   JButton btn43 = new JButton("Press 3");
	   JButton btn44 = new JButton("Press 4");
	   JButton btn45 = new JButton("Press 5");
	   JButton btn46 = new JButton("Press 6");
	   JButton btn47 = new JButton("Press 7");
	   JButton btn48 = new JButton("Press 8");
	   JButton btn49= new JButton("Press 1");
	   JButton btn50= new JButton("Press 2");
	   JButton btn51= new JButton("Press 3");
	   JButton btn52= new JButton("Press 4");
	   JButton btn53= new JButton("Press 5");
	   JButton btn54= new JButton("Press 6");
	   JButton btn55 = new JButton("Press 7");
	   JButton btn56 = new JButton("Press 8");
	   JButton btn57 = new JButton("Press 1");
	   JButton btn58 = new JButton("Press 2");
	   JButton btn59 = new JButton("Press 3");
	   JButton btn60 = new JButton("Press 4");
	   JButton btn61 = new JButton("Press 5");
	   JButton btn62 = new JButton("Press 6");
	   JButton btn63 = new JButton("Press 7");
	   JButton btn64 = new JButton("Press 8");
	   
	   JPanel panel = new JPanel(new GridLayout(8,8,1,1));
	   panel.add(btn1);
	   panel.add(btn2);
	   panel.add(btn3);
	   panel.add(btn4);
	   panel.add(btn5);
	   panel.add(btn6);
	   panel.add(btn7);
	   panel.add(btn8);
  	   panel.add(btn9);
	   panel.add(btn10);
	   panel.add(btn11);
	   panel.add(btn12);
	   panel.add(btn13);
	   panel.add(btn14);
	   panel.add(btn15);
	   panel.add(btn16);
	   panel.add(btn17);
	   panel.add(btn18);
	   panel.add(btn19);
	   panel.add(btn20);
	   panel.add(btn21);
	   panel.add(btn22);
	   panel.add(btn23);
	   panel.add(btn24);
	   panel.add(btn25);
	   panel.add(btn26);
	   panel.add(btn27);
	   panel.add(btn28);
	   panel.add(btn29);
	   panel.add(btn30);
	   panel.add(btn31);
	   panel.add(btn32);
	   panel.add(btn33);
	   panel.add(btn34);
	   panel.add(btn35);
	   panel.add(btn36);
	   panel.add(btn37);
	   panel.add(btn38);
	   panel.add(btn39);
	   panel.add(btn40);
	   panel.add(btn41);
	   panel.add(btn42);
	   panel.add(btn43);
	   panel.add(btn44);
	   panel.add(btn45);
	   panel.add(btn46);
	   panel.add(btn47);
	   panel.add(btn48);
	   panel.add(btn49);
	   panel.add(btn50);
	   panel.add(btn51);
	   panel.add(btn52);
	   panel.add(btn53);
	   panel.add(btn54);
	   panel.add(btn55);
	   panel.add(btn56);
	   panel.add(btn57);
	   panel.add(btn58);
	   panel.add(btn59);
	   panel.add(btn60);
	   panel.add(btn61);
	   panel.add(btn62);
	   panel.add(btn63);
	   panel.add(btn64);
	   
	   frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       frame.setSize(500,500);
	   
	   frame.getContentPane().add(panel);
      
       frame.setVisible(true);
    }
}